# Generated by Django 2.1.4 on 2019-01-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='pack',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
