# Generated by Django 2.1.4 on 2019-01-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0002_userprofileinfo_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='profit',
            field=models.CharField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
